version: "3.8"

services:
  rmq:
    image: rabbitmq:4.0.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rmq:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data/redis
